#!/bin/bash
function getport()
{
    	case $1 in
		SPU )
			local port=4001 ;;
		UCT )
			local port=10000 ;;
		FLUX )
			local port=8000 ;;
		AB )
			local port=4004 ;;
		SPU2 )
			local port=4010 ;;
		UCT2 )
			local port=4011 ;;
	esac
	echo "$port"
}

X="$(date +%s)";
R=$5;
NAME1=$1;
NAME2=$2;

PORT1=$(getport $NAME1)
PORT2=$(getport $NAME2);
START=$3;
PLAY=$4;
for ((i=0;i<$R;i++)); do
	java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT1 $NAME1 localhost $PORT2 $NAME2
	java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT2 $NAME2 localhost $PORT1 $NAME1
done
