#!/bin/bash
function getport()
{
    	case $1 in
		SPU )
			local port=4001 ;;
		UCT )
			local port=4002 ;;
		MC )
			local port=4003 ;;
		AB )
			local port=4004 ;;
	esac
	echo "$port"
}

X=$(date +%s);
FILE="out$X.data";
R=100;
NAME1=$1;
NAME2=$2;

PORT1=$(getport $NAME1)
PORT2=$(getport $NAME2);
START=$3;
PLAY=$4;
for ((i=0;i<$R;i++)); do
	java -cp $(cat classpath) apps.utilities.GameServerRunner test connect4 $START $PLAY localhost $PORT1 $NAME1 localhost $PORT2 $NAME2
	#OUT=$(java -jar ./lib/gamecontroller-cli-r466.jar M ./games/rulesheets/connect4.kif 15 15 1 -remote 1 SPUD localhost $PORT1 1 -remote 2 UCT localhost $PORT2 1)
	RES=$($OUT | grep 'Game over')
	set -- $RES;
	echo $OUT;
	echo " $NAME1 $5, $NAME2 $6" >> "out$X.data" #echo the result to the file
	echo " $NAME1 $5, $NAME2 $6" #echo the result to console

	RES=$(java -jar ./lib/gamecontroller-cli-r466.jar M ./games/rulesheets/connect4.kif 15 15 1 -remote 1 $NAME1 localhost $PORT1 1 -remote 2 $NAME2 localhost $PORT2 1 | grep 'Game over')
	set -- $RES;
	echo "-$NAME1 $6, $NAME2 $5" >> "out$X.data" #echo the result to the file
	echo "-$NAME1 $6, $NAME2 $5" #echo the result to console
done
