#!/bin/bash
function getport()
{
        case $1 in
                SPU )
                        local port=$((50000+$PBS_JOBID)) ;;
                UCT )
                        local port=$((50001+$PBS_JOBID)) ;;
                MC )
                        local port=40003 ;;
                AB )
                        local port=40004 ;;
                SPU2 )
                        local port=40010 ;;
                UCT2 )
                        local port=40011 ;;
        esac
        echo "$port"
}

NAME1=UCT;
NAME2=SPU;
SIGMA=$1
echo $SIGMA
PORT1=50000;
PORT2=50001;
START=15;
PLAY=15;
X="$(date +%s)-$SIGMA";
./uct $PORT1 &
./spu $PORT2 $SIGMA false &

sleep 3
echo running
java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT1 $NAME1 localhost $PORT2 $NAME2
java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT2 $NAME2 localhost $PORT1 $NAME1

killall java
