#!/bin/bash

NAME1=UCT;
NAME2=SPU;
SIGMA=$1
echo $SIGMA
PORT1=$((50000 + 2*$2));
PORT2=$((50001 + 2*$2));
START=15;
PLAY=15;
#X="$(date +%s)-$SIGMA";
X="$2-$SIGMA";
./uct $PORT1 & >> runu
./spu $PORT2 $SIGMA false & >> runf

sleep 3
echo running
java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT1 $NAME1 localhost $PORT2 $NAME2 >> runo
java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT2 $NAME2 localhost $PORT1 $NAME1 >> runo

