#!/bin/bash
function getport()
{
        case $1 in
                SPU )
                        local port=4001 ;;
                UCT )
                        local port=4002 ;;
                MC )
                        local port=4003 ;;
                AB )
                        local port=4004 ;;
                SPU2 )
                        local port=4010 ;;
                UCT2 )
                        local port=4011 ;;
        esac
        echo "$port"
}
X="$(date +%s)-$1";
NAME1=UCT;
NAME2=SPU;

PORT1=$(getport $NAME1);
PORT2=$(getport $NAME2);
START=15;
PLAY=15;
./uct &
./spu  $1 false &
sleep 3
java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT1 $NAME1 localhost $PORT2 $NAME2
java -cp $(cat classpath) apps.utilities.GameServerRunner $X connect4 $START $PLAY localhost $PORT2 $NAME2 localhost $PORT1 $NAME1
killall java
